global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: saf-control
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["saf-control:8080"]

  - job_name: client-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["client-service:8084"]

  - job_name: ville-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ville-service:8085"]

  - job_name: capteur-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["capteur-service:8086"]
