global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: saf-control
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["saf-control:8080"]

  - job_name: iot-runtime
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["iot-runtime:8081"]
